"""Added steps column

Revision ID: 968ca6ebde37
Revises: c0815fca8930
Create Date: 2023-09-06 16:24:27.545919

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '968ca6ebde37'
down_revision = 'c0815fca8930'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('steps', sa.JSON(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.drop_column('steps')

    # ### end Alembic commands ###
