"""added indexing

Revision ID: 99265a70a313
Revises: a3352cb448c7
Create Date: 2023-09-28 18:34:04.054909

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99265a70a313'
down_revision = 'a3352cb448c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('measured_ingredients', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_measured_ingredients_recipe_id'), ['recipe_id'], unique=False)

    with op.batch_alter_table('recipe_ingredients', schema=None) as batch_op:
        batch_op.create_index('idx_recipe_ingredients', ['recipe_id', 'ingredient_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe_ingredients', schema=None) as batch_op:
        batch_op.drop_index('idx_recipe_ingredients')

    with op.batch_alter_table('measured_ingredients', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_measured_ingredients_recipe_id'))

    # ### end Alembic commands ###
